name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel-${{ runner.os }}-${{ github.sha }}
        restore-keys: bazel-${{ runner.os }}-

    - name: Install bazelisk
      uses: bazelbuild/setup-bazelisk@v2

    - name: Build
      run: |
        bazel build //...

    - name: Test
      run: |
        bazel test //...