name: Minimal Bazel Build
on: [push]

jobs:
  build:
    name: Bazel
    runs-on: blacksmith
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.9.1
        with:
          disk-cache: true
          cache-version: 2

      - name: Clean bazel directories
        run: |
          sudo rm -rf /home/runner/.cache/bazel/_bazel_runner
          sudo rm -rf ~/.cache/bazel/_bazel_runner


      - name: Run bazel build
        run: |
          bazel \
            --bazelrc=.aspect/bazelrc/ci.bazelrc \
            build \
            --config=clippy \
            //...
